name: Passing the varibales inter and intra jobs
on:
    workflow_dispatch:
jobs:
    producer:
        runs-on: ubuntu-latest
        outputs:
            raghu: ${{ steps.generate-raghu.outputs.raghu }}
        steps:
          - name: Generate and export raghu
            id: generate-raghu
            run: |
              raghu = devops-guy

              echo "$raghu (Sent to output) >> ${GITHUB_OUTPUT}"
              echo "$raghu (sent to env)    >> ${GITHUB_ENV}"

          - name: Inspect the variable of raghu 
            run: |
              echo "$raghu with the ENV variable is" : $raghu
              echo "$raghu with the outputs is": ${{ steps.generate-raghu.outputs.raghu }}
    
    consumer:
        runs-on: ubuntu-latest
        needs: producer
        steps:
          - name: Reference from producer
            run: |
              echo "THe raghu value from producer is:" ${{ needs.producer.outputs.raghu}}