name: Passing the varibales inter and intra jobs-V3
on:
    workflow_dispatch:
jobs:
    producer:
        runs-on: ubuntu-latest
        outputs:
            raghu: ${{ steps.generate-raghu.outputs.raghu }}
        steps:
          - name: Generate and export raghu
            id: generate-raghu
            run: |
              raghu = devops-guy

              echo "raghu = $raghu" >> "$GITHUB_OUTPUT"
              echo "RAJESH = $raghu" >> "$GITHUB_ENV"

          - name: Inspect the variable of raghu 
            run: |
              echo "RAJESH with the ENV variable is" : $RAJESH
              echo "raghu with the outputs is": ${{ steps.generate-raghu.outputs.raghu }}
    
    consumer:
        runs-on: ubuntu-latest
        needs: producer
        steps:
          - name: Reference from producer
            run: |
              echo "THe raghu value from producer is: ${{ needs.producer.outputs.raghu }}"
              echo "RAJESH in consumer: ${RAJESH:-<UNSET>}"