name: Secrets and Environments
on:
    workflow_dispatch:

jobs:
    staging-environment:
        runs-on: ubuntu-latest
        environment: staging
        env:
            ENVIRONMENT_VARIABLE_STAGING: ${{ vars.ENVIRONMENT_VARIABLE_STAGING }}
            ENVIRONMENT_SECRET_STAGING: ${{ secrets.ENVIRONMENT_SECRET_STAGING }}
            REPO_SECRET: ${{ secrets.REPO_SECRET }}
            REPO_VARIABLE: ${{ vars.REPO_VARIABLE }}
        steps:
            run: |
              echo "ENV_VARIABLE_STAGING = $ENVIRONMENT_VARIALBLE_STAGING"
              echo "ENV_SECRET_STAGING   = $ENVIRONMENT_SECRET_STAGING"
              echo "REPO_VARIABLE        = $REPO_VARIABLE
              echo "REPO_SECRET          = $REPO_SECRET"

              
              

