name: Execute the shell script in Github Actions
on: push
jobs:
    shell_script_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7


            - name: Execute the script
              run: |
              
                 chmod +x ascii-shell-script.sh 
                ./ascii-shell-script.sh
 