name: Execute the shell script
on: push
jobs:
    shell_script:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v7

            - name: execute the script
              run: |
                   chmod +x ascii-shell-script.sh
                   ./ascii-shell-script.sh